// ====================== CROP DATA ======================
const crops = [
  {
    id:1, name:'Onion', marathi:'कांदा', icon:'🧅', cat:'Vegetables',
    color:'#FF6F00', colorLight:'#FFF3E0',
    season:'Rabi (Oct–Mar)', duration:'120–150 days',
    waterNeed:65, waterDesc:'Medium — 400–600 mm total',
    soil:'Well-drained loamy, pH 6.0–7.0', temp:'13–24°C',
    yield:'200–300 quintal/acre',
    cost:'₹25,000–35,000', income:'₹60,000–1,00,000', profit:'₹30,000–70,000',
    steps:[
      {title:'Land Preparation',desc:'Deep plough 2–3 times. Apply 10–15 tonnes FYM per acre. Level field for drainage.'},
      {title:'Nursery / Seed Sowing',desc:'Prepare nursery beds 1m wide. Sow seeds 1cm deep. 2–2.5 kg seed/acre. Transplant after 6–8 weeks.'},
      {title:'Transplanting',desc:'Rows: 15×10cm spacing. Avoid planting too deep — keep neck at soil level. Water immediately.'},
      {title:'Irrigation',desc:'First irrigation just after transplanting. Then every 7–10 days. Stop 10 days before harvest. Total 8–10 irrigations.'},
      {title:'Fertilizer',desc:'Basal: 50kg DAP + 25kg MOP/acre. Top dress: 30kg Urea at 30 days, 20kg at 45 days.'},
      {title:'Harvest',desc:'Harvest when 50–75% tops fall naturally. Cure in field 2–3 days. Store in cool, ventilated place.'},
    ],
    nutrients:[
      {name:'Nitrogen (N)',dose:'80–100 kg/acre',color:'#E3F2FD',tc:'#1565C0'},
      {name:'Phosphorus (P)',dose:'40–50 kg/acre',color:'#F3E5F5',tc:'#6A1B9A'},
      {name:'Potassium (K)',dose:'50–60 kg/acre',color:'#E8F5E9',tc:'#2E7D32'},
      {name:'Sulphur',dose:'20 kg/acre',color:'#FFFDE7',tc:'#F57F17'},
    ],
    diseases:[
      {name:'Purple Blotch',sym:'Purple spots on leaves, yellowing',remedy:'Mancozeb 75% WP @ 2g/L'},
      {name:'Thrips',sym:'Silver streaks on leaves, curling',remedy:'Spinosad 45% SC @ 0.3ml/L'},
      {name:'Basal Rot',sym:'Roots rotting, yellowing',remedy:'Avoid waterlogging. Carbendazim drench.'},
    ],
    tips:['Use certified disease-free seeds','Rabi onion gives better yield in Maharashtra','Store in well-ventilated shade nets','Foliar 19:19:19 spray boosts bulb size','Avoid excess nitrogen — causes thick neck'],
    climate:'Dry cool weather during bulb formation. Avoid frost. Good sunshine needed.',
  },
  {
    id:2, name:'Tomato', marathi:'टोमॅटो', icon:'🍅', cat:'Vegetables',
    color:'#C62828', colorLight:'#FFEBEE',
    season:'Rabi (Oct–Mar) Best', duration:'90–120 days',
    waterNeed:70, waterDesc:'Medium-high — 400–600 mm',
    soil:'Well-drained loamy, pH 6.0–7.0', temp:'20–30°C',
    yield:'150–300 quintal/acre',
    cost:'₹40,000–60,000', income:'₹80,000–1,50,000', profit:'₹40,000–90,000',
    steps:[
      {title:'Nursery',desc:'Sow in raised beds. Treat seeds with Thiram 3g/kg. Transplant at 25–30 days.'},
      {title:'Field Prep',desc:'FYM 8–10 tonnes/acre. Ridges and furrows for drip. Black plastic mulch is very beneficial.'},
      {title:'Transplanting',desc:'60×45cm spacing. Transplant in evening. Apply Trichoderma in planting hole.'},
      {title:'Staking',desc:'Stake at 30–40cm. Single or double stem training. Prune suckers for better fruit size.'},
      {title:'Fertilizer',desc:'Basal DAP 50kg + MOP 25kg. Top dress urea in splits. Micronutrient spray every 15 days.'},
      {title:'Harvest',desc:'Harvest at 25–50% red color. Firm stage for distant markets, full red for local.'},
    ],
    nutrients:[
      {name:'Nitrogen (N)',dose:'100–120 kg/acre',color:'#E3F2FD',tc:'#1565C0'},
      {name:'Phosphorus (P)',dose:'60–70 kg/acre',color:'#F3E5F5',tc:'#6A1B9A'},
      {name:'Potassium (K)',dose:'80–100 kg/acre',color:'#E8F5E9',tc:'#2E7D32'},
      {name:'Calcium',dose:'40 kg/acre',color:'#FFFDE7',tc:'#F57F17'},
      {name:'Boron',dose:'1–2 kg/acre',color:'#FBE9E7',tc:'#BF360C'},
    ],
    diseases:[
      {name:'Early Blight',sym:'Brown circular spots with rings on leaves',remedy:'Mancozeb 2g/L + Copper Oxychloride 3g/L'},
      {name:'Viral (TYLCV)',sym:'Yellow curling leaves, stunted growth',remedy:'Control whitefly with Imidacloprid. Remove infected plants.'},
      {name:'Fruit Borer',sym:'Larva enters fruit, rotting',remedy:'Spinosad 0.3ml/L or Emamectin Benzoate 0.5g/L'},
    ],
    tips:['Black plastic mulch increases yield 30–40%','Drip + fertigation is most profitable','Remove first flower cluster for better vegetative growth','Never plant same field two seasons in a row'],
    climate:'Warm days, cool nights ideal. Cannot tolerate frost or heat above 38°C.',
  },
  {
    id:3, name:'Wheat', marathi:'गहू', icon:'🌾', cat:'Grains',
    color:'#E65100', colorLight:'#FBE9E7',
    season:'Rabi (Nov–Mar)', duration:'120–150 days',
    waterNeed:50, waterDesc:'Medium — 450–650 mm',
    soil:'Heavy loam to clay loam, pH 6.0–7.5', temp:'10–25°C',
    yield:'18–30 quintal/acre',
    cost:'₹12,000–18,000', income:'₹22,000–45,000', profit:'₹10,000–25,000',
    steps:[
      {title:'Seed Treatment',desc:'Treat with Carboxin+Thiram @ 2.5g/kg for smut control. Biofertilizer treatment beneficial.'},
      {title:'Sowing',desc:'Line sowing at 20–22.5cm rows. 40–45 kg seed/acre for timely sown, 5cm depth.'},
      {title:'CRI Irrigation (Critical)',desc:'Crown Root Initiation at 20–25 days is most critical irrigation. Never miss. Light irrigation only.'},
      {title:'Remaining Irrigations',desc:'Tillering (40–45 days), Jointing (60 days), Flowering (80–85 days), Grain filling (100 days).'},
      {title:'Fertilizer',desc:'Basal DAP 50kg/acre. Urea 55kg at first irrigation, 27kg at second irrigation.'},
      {title:'Harvest',desc:'Harvest at physiological maturity (yellow straw, hard grain). Use combine harvester.'},
    ],
    nutrients:[
      {name:'Nitrogen (N)',dose:'55 kg/acre in 2 splits',color:'#E3F2FD',tc:'#1565C0'},
      {name:'Phosphorus (P)',dose:'25 kg/acre at sowing',color:'#F3E5F5',tc:'#6A1B9A'},
      {name:'Sulphur',dose:'15 kg/acre (gypsum)',color:'#FFFDE7',tc:'#F57F17'},
    ],
    diseases:[
      {name:'Yellow Rust',sym:'Yellow-orange powdery stripes on leaves',remedy:'Propiconazole 25% EC @ 1ml/L'},
      {name:'Loose Smut',sym:'Black powdery mass in place of grain',remedy:'Seed treatment with Carboxin+Thiram'},
      {name:'Aphids',sym:'Colonies on flag leaf and ear',remedy:'Dimethoate 30EC @ 1ml/L'},
    ],
    tips:['Timely sowing (Nov 1–25) is biggest yield factor','CRI irrigation — never skip even if only 1 irrigation possible','Choose MSH 47 or HD 3086 for Maharashtra','Avoid burning stubble — destroys beneficial organisms'],
    climate:'Cool dry winter. Frost sensitive at flowering. Late sowing after Dec 15 reduces yield.',
  },
  {
    id:4, name:'Soybean', marathi:'सोयाबीन', icon:'🫘', cat:'Pulses',
    color:'#558B2F', colorLight:'#F1F8E9',
    season:'Kharif (Jun–Sep)', duration:'90–110 days',
    waterNeed:55, waterDesc:'Moderate — 450–700 mm rainfed',
    soil:'Well-drained medium loam, pH 6.0–7.5', temp:'26–32°C',
    yield:'8–15 quintal/acre',
    cost:'₹10,000–15,000', income:'₹18,000–35,000', profit:'₹8,000–20,000',
    steps:[
      {title:'Seed Treatment',desc:'Rhizobium + PSB biofertilizer 200g each per 10kg seed. Reduces N need 50%. Add Thiram 3g/kg.'},
      {title:'Sowing',desc:'45cm rows, 5–7cm plant spacing. 25–30 kg seed/acre. Sow June 15–July 10. Depth 3–4cm.'},
      {title:'Weed Management',desc:'Critical in first 30–40 days. Imazethapyr 10% SL @ 750ml/acre at 15–20 days post-emergence.'},
      {title:'Fertilizer',desc:'Low N (20kg), P (25kg), K (12kg) per acre. Sulphur 20kg important. Rely on biofertilizer for N.'},
      {title:'Harvest',desc:'Harvest when 80–90% pods turn brown. Thresh immediately. Moisture 15–18% at harvest.'},
    ],
    nutrients:[
      {name:'Rhizobium (Bio)',dose:'200g/10kg seed',color:'#E8F5E9',tc:'#2E7D32'},
      {name:'Phosphorus (P)',dose:'25 kg/acre',color:'#F3E5F5',tc:'#6A1B9A'},
      {name:'Sulphur',dose:'20 kg/acre gypsum',color:'#FFFDE7',tc:'#F57F17'},
    ],
    diseases:[
      {name:'Yellow Mosaic Virus',sym:'Bright yellow patches on leaves',remedy:'Imidacloprid seed treatment. Thiamethoxam spray.'},
      {name:'Stem Fly',sym:'Maggots in stem base, plant wilts',remedy:'Imidacloprid 70% WS @ 7g/kg seed treatment'},
      {name:'Girdle Beetle',sym:'Circular cut on stem above ground',remedy:'Quinalphos 25 EC @ 2ml/L'},
    ],
    tips:['Biofertilizer seed treatment is most profitable investment','Broad-base furrow sowing prevents waterlogging on black soil','Yellow mosaic biggest threat — monitor aphids from Day 1','Timely sowing before July 15 is critical'],
    climate:'Warm humid kharif. Sensitive to waterlogging. Good drainage essential in black soils.',
  },
  {
    id:5, name:'Red Chilli', marathi:'लाल मिरची', icon:'🌶️', cat:'Spices',
    color:'#B71C1C', colorLight:'#FFEBEE',
    season:'Kharif + Rabi', duration:'150–180 days',
    waterNeed:60, waterDesc:'Medium — 600–750 mm',
    soil:'Sandy loam to loamy, pH 6.0–7.0', temp:'25–30°C',
    yield:'10–20 quintal dry/acre',
    cost:'₹30,000–45,000', income:'₹80,000–2,00,000', profit:'₹50,000–1,50,000',
    steps:[
      {title:'Nursery',desc:'200–250g seed/acre. Treat with Thiram 3g/kg. Transplant at 40–45 days.'},
      {title:'Transplanting',desc:'60×45cm spacing. Transplant in evening. Ridge-furrow system ideal.'},
      {title:'Irrigation',desc:'Drip saves 40% water and reduces disease. Critical at flowering. Every 7–10 days.'},
      {title:'Fertilizer',desc:'High K for color. NPK 80:40:60 kg/acre. Boron spray prevents flower drop.'},
      {title:'Harvest',desc:'Harvest green or red. Dry chilli: leave to turn red. Dry to 10–12% moisture.'},
    ],
    nutrients:[
      {name:'Nitrogen (N)',dose:'80 kg/acre in 3 splits',color:'#E3F2FD',tc:'#1565C0'},
      {name:'Potassium (K)',dose:'60 kg/acre',color:'#E8F5E9',tc:'#2E7D32'},
      {name:'Calcium+Boron',dose:'Foliar at flowering',color:'#FFFDE7',tc:'#F57F17'},
    ],
    diseases:[
      {name:'Thrips',sym:'Silvery streaks, leaf curl, flower drop',remedy:'Fipronil 5% SC @ 1ml/L + Neem oil 3ml/L'},
      {name:'Fruit Rot',sym:'Circular spots on fruits',remedy:'Copper Oxychloride 3g/L + Mancozeb 2g/L'},
      {name:'Bacterial Wilt',sym:'Sudden wilting without yellowing',remedy:'Soil solarization. No chemical cure.'},
    ],
    tips:['Boron spray at bud stage prevents flower drop','Pheromone traps for thrips monitoring','Crop rotation with cereals reduces wilt','Never allow standing water near roots'],
    climate:'Warm humid. Cannot tolerate frost. Sangli, Kolhapur, Nashik are major zones.',
  },
  {
    id:6, name:'Marigold', marathi:'झेंडू', icon:'🌼', cat:'Flowers',
    color:'#E65100', colorLight:'#FBE9E7',
    season:'Year-round', duration:'70–90 days',
    waterNeed:45, waterDesc:'Moderate — 400–500 mm',
    soil:'Any well-drained soil, pH 5.5–7.5', temp:'15–30°C',
    yield:'40–80 quintal flowers/acre',
    cost:'₹15,000–20,000', income:'₹50,000–1,20,000', profit:'₹30,000–80,000',
    steps:[
      {title:'Nursery',desc:'400–500g seed/acre. Germination 5–7 days. Transplant at 25–30 days.'},
      {title:'Transplanting',desc:'45×30cm spacing. Transplant in evening. Irrigate immediately.'},
      {title:'Pinching',desc:'Pinch growing tip at 40 days. Promotes branching and more flowers — critical step.'},
      {title:'Fertilizer',desc:'NPK 60:30:30 kg/acre. Top dress 20kg urea at flowering.'},
      {title:'Harvest',desc:'Harvest when fully open (local) or 3/4 open (distant). Every 7–10 days.'},
    ],
    nutrients:[
      {name:'Nitrogen (N)',dose:'60 kg/acre',color:'#E3F2FD',tc:'#1565C0'},
      {name:'Phosphorus (P)',dose:'30 kg/acre',color:'#F3E5F5',tc:'#6A1B9A'},
      {name:'FYM / Compost',dose:'5–8 tonnes/acre',color:'#F1F8E9',tc:'#558B2F'},
    ],
    diseases:[
      {name:'Powdery Mildew',sym:'White powder on leaves and flowers',remedy:'Sulphur 3g/L + Carbendazim 1g/L'},
      {name:'Flower Bud Thrips',sym:'Deformed flowers, buds fail to open',remedy:'Spinosad 0.3ml/L on buds'},
    ],
    tips:['Plant before Diwali/Dussehra for premium festival price','Pinching is most important management practice','Neem oil spray prevents 60% of insect pests','Marigold as border crop repels pests in vegetable fields'],
    climate:'Wide adaptability. Best color in cool weather. High demand during festival season.',
  },
  {
    id:7, name:'Sugarcane', marathi:'ऊस', icon:'🎋', cat:'Cash Crops',
    color:'#1B5E20', colorLight:'#E8F5E9',
    season:'Adsali (Jul) / Suru (Oct)', duration:'12–18 months',
    waterNeed:90, waterDesc:'Very high — 1500–2500 mm',
    soil:'Deep well-drained loam, pH 6.0–7.5', temp:'27–38°C',
    yield:'400–600 quintal/acre',
    cost:'₹60,000–80,000', income:'₹1,20,000–2,00,000', profit:'₹50,000–1,20,000',
    steps:[
      {title:'Variety Selection',desc:'Co 86032, CoM 265 for Maharashtra. Choose variety for your factory zone.'},
      {title:'Seed Material',desc:'Use 3-budded setts from disease-free crop. Treat with Carbendazim 0.1%. 5–6 tonnes sett/acre.'},
      {title:'Planting',desc:'120–150cm row spacing. Flat or trench method. Gap filling at 30 days.'},
      {title:'Drip Irrigation',desc:'Drip + fertigation gives 30–40% more yield with 50% less water. Strongly recommended.'},
      {title:'Trash Mulching',desc:'Spread dry leaves between rows at 90 days. Saves 3–4 irrigations, controls weeds.'},
      {title:'Harvest',desc:'Harvest at 12 months for Suru, 18 for Adsali. Transport to factory within 24 hours.'},
    ],
    nutrients:[
      {name:'Nitrogen (N)',dose:'150–200 kg/acre in 5 splits',color:'#E3F2FD',tc:'#1565C0'},
      {name:'Phosphorus (P)',dose:'60 kg/acre at planting',color:'#F3E5F5',tc:'#6A1B9A'},
      {name:'Potassium (K)',dose:'80–100 kg/acre',color:'#E8F5E9',tc:'#2E7D32'},
      {name:'Press Mud / FYM',dose:'5 tonnes/acre',color:'#F1F8E9',tc:'#558B2F'},
    ],
    diseases:[
      {name:'Red Rot',sym:'Red discoloration in stalk pith',remedy:'Use disease-free setts. No chemical cure.'},
      {name:'Top Borer',sym:'Dead heart in young crop',remedy:'Trichogramma parasites. Chlorantraniliprole GR.'},
      {name:'Pyrilla',sym:'Yellow dried leaves, sooty mold',remedy:'Malathion 50 EC @ 1ml/L'},
    ],
    tips:['Drip + fertigation gives best ROI','Ratoon crop saves 50% planting cost','Trash mulching saves 3–4 irrigations','Deliver to factory within 24 hours of harvest'],
    climate:'Tropical. Maharashtra sugarbelt: Kolhapur, Pune, Nashik, Satara.',
  },
  {
    id:8, name:'Grapes', marathi:'द्राक्षे', icon:'🍇', cat:'Fruits',
    color:'#4A148C', colorLight:'#EDE7F6',
    season:'Pruning Oct, Fruiting Feb–Apr', duration:'Perennial',
    waterNeed:75, waterDesc:'High — 600–800 mm, drip essential',
    soil:'Deep sandy loam, pH 6.5–7.5', temp:'25–35°C',
    yield:'8–15 tonnes/acre (table)',
    cost:'₹2,00,000–3,00,000 (estab.)', income:'₹3,00,000–8,00,000', profit:'₹1,50,000–5,00,000',
    steps:[
      {title:'Variety',desc:'Thompson Seedless (export), Sharad Seedless (local). Nashik belt is ideal.'},
      {title:'Establishment',desc:'Pits 60×60×60cm. 3m×1.5m spacing on pandal. Heavy initial infrastructure investment.'},
      {title:'Pruning',desc:'Two prunings: April (back) + October (fruit). Most technical management practice.'},
      {title:'Bunch Management',desc:'Girdling forces berry development. Berry thinning, bunch shaping for export quality.'},
      {title:'Harvest',desc:'Harvest at 18–22% Brix sugar. Early morning. Handle gently — one bunch at a time.'},
    ],
    nutrients:[
      {name:'Nitrogen (N)',dose:'150 kg/acre/year',color:'#E3F2FD',tc:'#1565C0'},
      {name:'Potassium (K)',dose:'200 kg/acre/year',color:'#E8F5E9',tc:'#2E7D32'},
      {name:'Zinc + Boron',dose:'Foliar spray monthly',color:'#FBE9E7',tc:'#BF360C'},
    ],
    diseases:[
      {name:'Downy Mildew',sym:'Oil spots on leaves, white mold on bunches',remedy:'Metalaxyl+Mancozeb 2.5g/L'},
      {name:'Powdery Mildew',sym:'White powdery growth on shoots',remedy:'Sulphur 80% WP @ 3g/L'},
      {name:'Mealybug',sym:'White waxy insects on bunches',remedy:'Profenofos 50% EC @ 2ml/L'},
    ],
    tips:['Drip + fertigation is non-negotiable','Join FPC for export access','Pre-harvest pesticide gap: 15–21 days for export','Soil testing before each season'],
    climate:'Hot dry summers, mild winters. Nashik is ideal. Rain during fruiting is damaging.',
  },
];

// ====================== MARKET PRICES ======================
const priceData = [
  {name:'Onion (Kanda)',icon:'🧅',cat:'Vegetables',min:1200,max:1850,modal:1550,unit:'quintal',change:+80},
  {name:'Tomato (Tamatar)',icon:'🍅',cat:'Vegetables',min:8,max:22,modal:15,unit:'kg',change:-3},
  {name:'Potato (Batata)',icon:'🥔',cat:'Vegetables',min:900,max:1400,modal:1100,unit:'quintal',change:+50},
  {name:'Brinjal (Wangi)',icon:'🍆',cat:'Vegetables',min:10,max:28,modal:18,unit:'kg',change:0},
  {name:'Spinach (Palak)',icon:'🥬',cat:'Vegetables',min:12,max:30,modal:20,unit:'kg',change:+5},
  {name:'Wheat (Gehun)',icon:'🌾',cat:'Grains',min:2050,max:2300,modal:2180,unit:'quintal',change:0},
  {name:'Maize (Makka)',icon:'🌽',cat:'Grains',min:1400,max:1700,modal:1560,unit:'quintal',change:+40},
  {name:'Rice (Tandool)',icon:'🍚',cat:'Grains',min:2500,max:3200,modal:2850,unit:'quintal',change:+100},
  {name:'Soybean (Soya)',icon:'🫘',cat:'Pulses',min:4200,max:4600,modal:4450,unit:'quintal',change:+120},
  {name:'Tur Dal (Arhar)',icon:'🫘',cat:'Pulses',min:6800,max:7400,modal:7100,unit:'quintal',change:-200},
  {name:'Grapes (Draksha)',icon:'🍇',cat:'Fruits',min:40,max:90,modal:65,unit:'kg',change:0},
  {name:'Pomegranate',icon:'🍎',cat:'Fruits',min:55,max:130,modal:90,unit:'kg',change:+10},
  {name:'Banana (Keli)',icon:'🍌',cat:'Fruits',min:20,max:45,modal:32,unit:'kg',change:-3},
  {name:'Red Chilli (Mirchi)',icon:'🌶️',cat:'Spices',min:8000,max:12000,modal:10000,unit:'quintal',change:+500},
  {name:'Coriander (Kothimbir)',icon:'🌿',cat:'Spices',min:12,max:30,modal:20,unit:'kg',change:+5},
];

// ====================== PRODUCTS ======================
const products = [
  {id:1,name:'Onion (Kanda)',marathi:'कांदा',icon:'🧅',cat:'Vegetables',price:18,unit:'kg',farmer:'Raju Patil',location:'Nandurbar',organic:true,stock:500,badge:'Best Seller'},
  {id:2,name:'Tomato (Tamatar)',marathi:'टोमॅटो',icon:'🍅',cat:'Vegetables',price:15,unit:'kg',farmer:'Suresh Nikam',location:'Dhule',organic:false,stock:200,badge:null},
  {id:3,name:'Grapes (Draksha)',marathi:'द्राक्षे',icon:'🍇',cat:'Fruits',price:65,unit:'kg',farmer:'Anil Shinde',location:'Nashik',organic:true,stock:80,badge:'Seasonal'},
  {id:4,name:'Wheat (Gehun)',marathi:'गहू',icon:'🌾',cat:'Grains',price:22,unit:'kg',farmer:'Vijay More',location:'Dhule',organic:false,stock:1000,badge:null},
  {id:5,name:'Spinach (Palak)',marathi:'पालक',icon:'🥬',cat:'Vegetables',price:20,unit:'kg',farmer:'Savita Deshmukh',location:'Shirpur',organic:true,stock:30,badge:'Organic'},
  {id:6,name:'Soybean (Soya)',marathi:'सोयाबीन',icon:'🫘',cat:'Pulses',price:45,unit:'kg',farmer:'Ganesh Borse',location:'Shahada',organic:false,stock:400,badge:null},
  {id:7,name:'Maize (Makka)',marathi:'मका',icon:'🌽',cat:'Grains',price:16,unit:'kg',farmer:'Ramesh Chavan',location:'Sakri',organic:false,stock:600,badge:null},
  {id:8,name:'Pomegranate',marathi:'डाळिंब',icon:'🍎',cat:'Fruits',price:90,unit:'kg',farmer:'Anil Shinde',location:'Nashik',organic:true,stock:60,badge:'Premium'},
  {id:9,name:'Potato (Batata)',marathi:'बटाटा',icon:'🥔',cat:'Vegetables',price:25,unit:'kg',farmer:'Raju Patil',location:'Nandurbar',organic:false,stock:800,badge:'Best Seller'},
  {id:10,name:'Tur Dal',marathi:'तूर डाळ',icon:'🫘',cat:'Pulses',price:71,unit:'kg',farmer:'Ganesh Borse',location:'Shahada',organic:false,stock:200,badge:null},
  {id:11,name:'Red Chilli',marathi:'मिरची',icon:'🌶️',cat:'Spices',price:100,unit:'kg',farmer:'Vijay More',location:'Dhule',organic:false,stock:50,badge:'Hot'},
  {id:12,name:'Banana (Keli)',marathi:'केळी',icon:'🍌',cat:'Fruits',price:32,unit:'kg',farmer:'Priya Jadhav',location:'Dhule',organic:false,stock:300,badge:null},
  {id:13,name:'Coriander (Kothimbir)',marathi:'कोथिंबीर',icon:'🌿',cat:'Spices',price:20,unit:'kg',farmer:'Savita Deshmukh',location:'Shirpur',organic:true,stock:40,badge:'Fresh'},
  {id:14,name:'Brinjal (Wangi)',marathi:'वांगी',icon:'🍆',cat:'Vegetables',price:18,unit:'kg',farmer:'Suresh Nikam',location:'Dhule',organic:false,stock:150,badge:null},
];

// ====================== FARMERS ======================
const farmers = [
  {id:1,name:'Raju Ramesh Patil',icon:'👨‍🌾',location:'Nandurbar, Maharashtra',crops:['🧅 Onion','🥔 Potato','🍅 Tomato'],rating:4.9,reviews:128,phone:'9876543210',acres:12,experience:'15 years'},
  {id:2,name:'Savita Arun Deshmukh',icon:'👩‍🌾',location:'Shirpur, Dhule',crops:['🥬 Spinach','🌿 Coriander','🍋 Lemon'],rating:4.8,reviews:96,phone:'9876543211',acres:8,experience:'10 years'},
  {id:3,name:'Anil Santosh Shinde',icon:'👨‍🌾',location:'Nashik, Maharashtra',crops:['🍇 Grapes','🍎 Pomegranate','🧅 Onion'],rating:4.7,reviews:210,phone:'9876543212',acres:25,experience:'22 years'},
  {id:4,name:'Ganesh Bapu Borse',icon:'👨‍🌾',location:'Shahada, Nandurbar',crops:['🫘 Soybean','🌾 Wheat','🫘 Tur Dal'],rating:5.0,reviews:64,phone:'9876543213',acres:18,experience:'18 years'},
  {id:5,name:'Suresh Kisan Nikam',icon:'👨‍🌾',location:'Dhule, Maharashtra',crops:['🍅 Tomato','🍆 Brinjal','🥦 Cauliflower'],rating:4.6,reviews:77,phone:'9876543214',acres:6,experience:'8 years'},
  {id:6,name:'Priya Manoj Jadhav',icon:'👩‍🌾',location:'Dhule, Maharashtra',crops:['🍋 Lemon','🍌 Banana','🌶️ Chilli'],rating:4.8,reviews:143,phone:'9876543215',acres:10,experience:'12 years'},
  {id:7,name:'Vijay Tukaram More',icon:'👨‍🌾',location:'Dhule, Maharashtra',crops:['🌾 Wheat','🌽 Maize','🌶️ Chilli'],rating:4.5,reviews:55,phone:'9876543216',acres:20,experience:'20 years'},
  {id:8,name:'Ramesh Bhimrao Chavan',icon:'👨‍🌾',location:'Sakri, Dhule',crops:['🌽 Maize','🍚 Rice','🌾 Wheat'],rating:4.7,reviews:89,phone:'9876543217',acres:15,experience:'16 years'},
];